# This configuration only exposes OpenWebUI to the host machine.
# You can easily expose more services by uncommenting the ports section for each service.

x-common: &common
  restart: unless-stopped
  environment:
    - TZ=${TZ:-Europe/Oslo}
  networks:
    - ai-network

x-gpu-reservation: &gpu_reservation
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities:
              - gpu

networks:
  ai-network:
    driver: bridge

services:
  open-webui:
    <<: [ *common, *gpu_reservation ]
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - ${PORT_OPENWEBUI:-3000}:8080
    env_file:
      - open-webui/open-webui.env
      - open-webui/comfy-workflow.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - COMFYUI_BASE_URL=http://comfyui:8188
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://kokoro-tts:8880/v1
      - PLAYWRIGHT_WS_URL=ws://playwright:9323

  ollama:
    <<: [ *common, *gpu_reservation ]
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./data/ollama:/root/.ollama
    # ports:
    #   - "${PORT_OLLAMA:-11434}:11434"
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-20}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-""}

  kokoro-tts:
    <<: [ *common, *gpu_reservation ]
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    container_name: kokoro-tts
    volumes:
      - ./data/kokoro-tts:/app/api/src/models
    user: "root"
    # ports:
    #   - "${PORT_KOKORO:-8880}:8880"
    environment:
      - PYTHONPATH=/app:/app/api
      - USE_GPU=true
      - PYTHONUNBUFFERED=1

  comfyui:
    <<: [ *common, *gpu_reservation ]
    container_name: comfyui
    image: ghcr.io/arsac/comfyui-flux:latest
    volumes:
      - ./data/comfyui:/app
    env_file: comfy/comfy.env
    # ports:
    #   - "${PORT_COMFYUI:-8188}:8188"
    environment:
      - HF_TOKEN=${HF_TOKEN}

  playwright:
    <<: *common
    image: mcr.microsoft.com/playwright:latest
    container_name: playwright
    # ports:
    #   - "${PORT_PLAYWRIGHT:-9323}:9323"